Update clause_1.adoc
opengeospatial/geosemantics-dwg pull request #38
Opened 2020-01-11 22:11 UTC by Fransie

Add section about Linked Data, add invitation to review and collaborate.

2020-01-14 00:54 UTC, Fransie commented
Extension of the introduction, adding a bit about Linked Data, aligning the introduction with the three chapters, and adding that the goal of the white paper is invoking involvement by potential users and investment by the OGC.

2020-01-14 12:04 UTC, jabhay requested changes
Looks good. Just the one suggestion prior to acceptance. P.S. you've really got a knack for words. Great writing!

2020-01-14 12:04 UTC, jabhay commented on white_paper/clause_1.adoc
> +Semantic technologies, in the scope of this document, relate to the use of formal ontologies to describe concepts: the relationships between "things" and categories of "things". There are a number of
```suggestion
Semantic technologies, in the scope of this document, relate to the use of formal ontologies to describe concepts: the relationships between "things" and categories of "things". There are a number of goals for using these technologies, which often relate to providing the capability to reason over the data and simplified dealing with heterogeneous data sources. Example goals include enabling machine readability, and federated searching. A major area in which semantic technologies are used is the Semantic Web, the part of the World Wide Web dealing with semantics.
```

2020-01-16 22:15 UTC, TallTed commented on white_paper/clause_1.adoc
> +Although many current and past work within the OGC involves semantic and graph technologies, there is one main applicable OGC standard: GeoSPARQL. GeoSPARQL offers both semantics for representing geo
```suggestion
Although much current and past work within the OGC involves semantic and graph technologies, there is only one applicable OGC standard: GeoSPARQL. GeoSPARQL both offers semantics for representing geospatial data, and specifies how geospatial data that are expressed using the Resource Description Framework (RDF) can be queried using SPARQL, the query language for RDF. 
```

2020-01-19 09:16 UTC, jabhay approved these changes

2020-01-19 09:17 UTC, merged